create extension if not exists pgcrypto;

create schema if not exists private;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workspaces (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(trim(name)) between 2 and 120),
  kind text not null default 'personal' check (kind in ('personal','client','business')),
  owner_id uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workspace_members (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'viewer' check (role in ('owner','admin','editor','viewer','custom')),
  permissions jsonb not null default '{"finance":{"view":true,"write":false},"open_finance":{"view":false,"manage":false},"investments":{"view":false,"write":false},"users":{"manage":false}}'::jsonb,
  status text not null default 'active' check (status in ('active','invited','suspended')),
  invited_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workspace_id, user_id)
);

create table if not exists public.financial_entities (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  entity_type text not null check (entity_type in ('transactions','accounts','cards','categories','investments','settings')),
  local_id text not null,
  data jsonb not null default '{}'::jsonb,
  version bigint not null default 1,
  deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workspace_id, entity_type, local_id)
);

create index if not exists idx_financial_entities_workspace_type_updated
  on public.financial_entities(workspace_id, entity_type, updated_at desc);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  workspace_id uuid references public.workspaces(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_log_workspace_created
  on public.audit_log(workspace_id, created_at desc);

create or replace function private.is_platform_admin()
returns boolean
language sql
stable
security invoker
set search_path = pg_catalog
as $$
  select coalesce(((select auth.jwt())->'app_metadata'->>'platform_admin')::boolean, false)
$$;

create or replace function private.default_owner_permissions()
returns jsonb
language sql
immutable
security invoker
set search_path = pg_catalog
as $$
  select '{"finance":{"view":true,"write":true},"open_finance":{"view":true,"manage":true},"investments":{"view":true,"write":true},"users":{"manage":true}}'::jsonb
$$;

create or replace function private.handle_workspace_insert()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
begin
  insert into public.workspace_members(workspace_id, user_id, role, permissions, status)
  values (new.id, new.owner_id, 'owner', private.default_owner_permissions(), 'active')
  on conflict (workspace_id, user_id) do update
    set role = 'owner', permissions = private.default_owner_permissions(), status = 'active', updated_at = now();
  return new;
end;
$$;

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
declare
  workspace_name text;
begin
  insert into public.profiles(id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(nullif(new.raw_user_meta_data->>'display_name',''), split_part(coalesce(new.email,'Usuário'),'@',1))
  )
  on conflict (id) do nothing;

  workspace_name := coalesce(nullif(new.raw_user_meta_data->>'display_name',''), split_part(coalesce(new.email,'Usuário'),'@',1)) || ' — Pessoal';
  insert into public.workspaces(name, kind, owner_id)
  values (workspace_name, 'personal', new.id);
  return new;
end;
$$;

revoke all on function private.is_platform_admin() from public, anon;
revoke all on function private.default_owner_permissions() from public, anon, authenticated;
revoke all on function private.handle_workspace_insert() from public, anon, authenticated;
revoke all on function private.handle_new_user() from public, anon, authenticated;
grant execute on function private.is_platform_admin() to authenticated;

DROP TRIGGER IF EXISTS trg_workspace_owner_membership ON public.workspaces;
create trigger trg_workspace_owner_membership
after insert on public.workspaces
for each row execute function private.handle_workspace_insert();

DROP TRIGGER IF EXISTS trg_auth_user_bootstrap ON auth.users;
create trigger trg_auth_user_bootstrap
after insert on auth.users
for each row execute function private.handle_new_user();

alter table public.profiles enable row level security;
alter table public.workspaces enable row level security;
alter table public.workspace_members enable row level security;
alter table public.financial_entities enable row level security;
alter table public.audit_log enable row level security;

create policy "profiles_select_self_or_platform_admin"
on public.profiles for select
to authenticated
using ((select auth.uid()) = id or private.is_platform_admin());

create policy "profiles_update_self"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy "members_select_self_or_platform_admin"
on public.workspace_members for select
to authenticated
using (user_id = (select auth.uid()) or private.is_platform_admin());

create policy "workspaces_select_member_or_platform_admin"
on public.workspaces for select
to authenticated
using (
  private.is_platform_admin()
  or exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = workspaces.id
      and wm.user_id = (select auth.uid())
      and wm.status = 'active'
  )
);

create policy "workspaces_insert_owner"
on public.workspaces for insert
to authenticated
with check (owner_id = (select auth.uid()) or private.is_platform_admin());

create policy "workspaces_update_owner_or_platform_admin"
on public.workspaces for update
to authenticated
using (owner_id = (select auth.uid()) or private.is_platform_admin())
with check (owner_id = (select auth.uid()) or private.is_platform_admin());

create policy "workspaces_delete_owner_or_platform_admin"
on public.workspaces for delete
to authenticated
using (owner_id = (select auth.uid()) or private.is_platform_admin());

create policy "financial_entities_select_workspace_member"
on public.financial_entities for select
to authenticated
using (
  private.is_platform_admin()
  or exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = financial_entities.workspace_id
      and wm.user_id = (select auth.uid())
      and wm.status = 'active'
      and coalesce((wm.permissions->'finance'->>'view')::boolean, true)
      and (
        financial_entities.entity_type <> 'investments'
        or wm.role in ('owner','admin')
        or coalesce((wm.permissions->'investments'->>'view')::boolean, false)
      )
  )
);

create policy "financial_entities_insert_workspace_writer"
on public.financial_entities for insert
to authenticated
with check (
  private.is_platform_admin()
  or exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = financial_entities.workspace_id
      and wm.user_id = (select auth.uid())
      and wm.status = 'active'
      and (
        wm.role in ('owner','admin')
        or coalesce((wm.permissions->'finance'->>'write')::boolean, false)
      )
      and (
        financial_entities.entity_type <> 'investments'
        or wm.role in ('owner','admin')
        or coalesce((wm.permissions->'investments'->>'write')::boolean, false)
      )
  )
);

create policy "financial_entities_update_workspace_writer"
on public.financial_entities for update
to authenticated
using (
  private.is_platform_admin()
  or exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = financial_entities.workspace_id
      and wm.user_id = (select auth.uid())
      and wm.status = 'active'
      and (wm.role in ('owner','admin') or coalesce((wm.permissions->'finance'->>'write')::boolean, false))
  )
)
with check (
  private.is_platform_admin()
  or exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = financial_entities.workspace_id
      and wm.user_id = (select auth.uid())
      and wm.status = 'active'
      and (wm.role in ('owner','admin') or coalesce((wm.permissions->'finance'->>'write')::boolean, false))
  )
);

create policy "financial_entities_delete_workspace_writer"
on public.financial_entities for delete
to authenticated
using (
  private.is_platform_admin()
  or exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = financial_entities.workspace_id
      and wm.user_id = (select auth.uid())
      and wm.status = 'active'
      and (wm.role in ('owner','admin') or coalesce((wm.permissions->'finance'->>'write')::boolean, false))
  )
);

create policy "audit_select_workspace_admin"
on public.audit_log for select
to authenticated
using (
  private.is_platform_admin()
  or exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = audit_log.workspace_id
      and wm.user_id = (select auth.uid())
      and wm.status = 'active'
      and (wm.role in ('owner','admin') or coalesce((wm.permissions->'users'->>'manage')::boolean, false))
  )
);

create policy "audit_insert_workspace_member"
on public.audit_log for insert
to authenticated
with check (
  actor_user_id = (select auth.uid())
  and (
    private.is_platform_admin()
    or exists (
      select 1 from public.workspace_members wm
      where wm.workspace_id = audit_log.workspace_id
        and wm.user_id = (select auth.uid())
        and wm.status = 'active'
    )
  )
);

grant usage on schema public to authenticated;
grant select, update on public.profiles to authenticated;
grant select, insert, update, delete on public.workspaces to authenticated;
grant select on public.workspace_members to authenticated;
grant select, insert, update, delete on public.financial_entities to authenticated;
grant select, insert on public.audit_log to authenticated;
grant usage, select on sequence public.audit_log_id_seq to authenticated;
